"use client";
import { useState } from "react";
import { Icon } from "./Icon";
import { WhatsAppCta } from "./WhatsAppCta";

const faqs = [
  ["Por que eu pagaria R$ 99 por um endereço?", "Porque o serviço atende a uma necessidade empresarial específica: ter um endereço empresarial em Natal para utilização no CNPJ, com recebimento de correspondências e gestão de encomendas, sem que você precise manter um escritório físico para essa finalidade. Além disso, clientes de Endereço Fiscal têm 35% de desconto no uso das salas de reuniões do NVO."],
  ["Posso usar o endereço da minha casa?", "Pode existir essa possibilidade dependendo do seu caso. A proposta do Endereço Fiscal é oferecer uma referência empresarial em Natal diferente do endereço residencial, para quem não quer utilizar a própria residência como endereço empresarial. Consequências jurídicas, tributárias, cadastrais ou de privacidade dependem do caso e devem ser confirmadas."],
  ["Preciso realmente de um escritório?", "Não é essa a proposta. O Endereço Fiscal atende à necessidade de ter um endereço empresarial em Natal sem necessariamente manter um escritório físico para essa finalidade. Se você precisar utilizar uma sala de reunião no NVO, clientes de Endereço Fiscal têm 35% de desconto no uso das salas de reuniões."],
  ["Minha empresa é de outra cidade.", "Essa é uma das situações para as quais a solução pode fazer sentido: sua empresa pode precisar estabelecer uma presença empresarial em Natal sem necessariamente manter um escritório físico na cidade. O serviço oferece um endereço em Natal para utilização no CNPJ. A adequação ao caso específico deve ser confirmada quando houver exigências particulares."],
  ["O que exatamente está incluído?", "O que está confirmado na oferta é: endereço para utilização no CNPJ, recebimento de correspondências e gestão de encomendas. Clientes de Endereço Fiscal também têm 35% de desconto no uso das salas de reuniões do NVO. Demais condições comerciais e operacionais ainda precisam ser confirmadas."],
  ["O que acontece com minhas correspondências e encomendas?", "O serviço inclui recebimento de correspondências e gestão de encomendas. Detalhes sobre aviso, retirada, armazenamento, prazos, responsáveis e procedimentos operacionais precisam ser confirmados no atendimento comercial."],
  ["Posso confiar em colocar meu CNPJ nesse endereço?", "O Endereço Fiscal do NVO oferece endereço para utilização no CNPJ. A estrutura onde o serviço é oferecido está em imóvel próprio e possui licenças atualizadas. O NVO atua há 16 anos no mercado. A adequação automática para qualquer CNPJ, atividade ou órgão não é uma garantia; casos específicos devem ser confirmados no atendimento comercial."],
] as const;

export function FAQ() {
  const [open, setOpen] = useState<number | null>(0);
  return <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-5xl"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-[#F89F27]">Dúvidas</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#332e2f] sm:text-4xl">Antes de falar com o NVO, talvez você esteja se perguntando:</h2></div><div className="mt-10 space-y-3">{faqs.map(([question,answer],i)=>{const isOpen=open===i; return <article key={question} className="overflow-hidden rounded-lg border border-[#332e2f]/10"><button type="button" onClick={()=>setOpen(isOpen?null:i)} aria-expanded={isOpen} className="flex w-full items-center justify-between gap-6 px-5 py-5 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#F89F27] sm:px-6"><span className="font-semibold text-[#332e2f]">{question}</span><span className="shrink-0 text-[#F89F27]"><Icon name={isOpen?"minus":"plus"}/></span></button>{isOpen&&<div className="border-t border-[#332e2f]/10 px-5 pb-6 pt-5 text-sm leading-7 text-[#332e2f]/70 sm:px-6">{answer}</div>}</article>})}</div><div className="mt-8"><WhatsAppCta/></div></div></section>;
}
